"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowDownRight, ArrowUpRight, BadgeEuro, Banknote, BarChart3, Building2, CheckCircle2, CircleDollarSign, FileBarChart, FileUp, Gauge, Home, Landmark, Lock, Menu, PieChart as PieIcon, TrendingUp, Wallet, X } from "lucide-react";

type Status = "green" | "yellow" | "red";
type Page = "cockpit" | "standorte" | "analysen" | "bwa" | "cashflow" | "plan" | "darlehen" | "uploads" | "reports";
type Auth = "welcome" | "login" | "firstPassword" | "firstPin" | "forgot" | "app";

type Standort = {
  id: string; name: string; start: string; status: Status; leistung: number; pvs: number; honorar: number; eigenlabor: number; ebitda: number; marge: number; cashflow: number; konto: number; forderungen: number; plan: number;
  kosten: { material: number; fremdlabor: number; sonstige: number; gesamt: number };
  debt: { kaufpreis: number; darlehen: number; rest: number; tilgung: number; zins: number; earnTotal: number; earnPaid: number; ziel: number; ist: number };
};

const sites: Standort[] = [
  { id:"kirchberg", name:"Kirchberg", start:"01.07.2024", status:"green", leistung:1184000, pvs:1138000, honorar:1014000, eigenlabor:124000, ebitda:213000, marge:18.0, cashflow:82000, konto:246000, forderungen:168000, plan:4.8, kosten:{material:8.8,fremdlabor:13.6,sonstige:33.1,gesamt:65.5}, debt:{kaufpreis:1320000,darlehen:860000,rest:704000,tilgung:96000,zins:36000,earnTotal:260000,earnPaid:151000,ziel:205000,ist:213000}},
  { id:"essen", name:"Essen", start:"01.01.2025", status:"yellow", leistung:944000, pvs:912000, honorar:844000, eigenlabor:68000, ebitda:96000, marge:10.2, cashflow:-18000, konto:104000, forderungen:142000, plan:-3.7, kosten:{material:10.4,fremdlabor:15.9,sonstige:39.2,gesamt:72.1}, debt:{kaufpreis:980000,darlehen:710000,rest:642000,tilgung:62000,zins:31000,earnTotal:190000,earnPaid:52000,ziel:124000,ist:96000}},
  { id:"kehl", name:"Kehl", start:"01.04.2025", status:"yellow", leistung:752000, pvs:724000, honorar:657000, eigenlabor:67000, ebitda:79000, marge:10.5, cashflow:21000, konto:132000, forderungen:121000, plan:-1.8, kosten:{material:11.6,fremdlabor:18.4,sonstige:41.7,gesamt:75.1}, debt:{kaufpreis:820000,darlehen:610000,rest:574000,tilgung:44000,zins:27000,earnTotal:150000,earnPaid:38000,ziel:92000,ist:79000}},
  { id:"ulmet", name:"Ulmet", start:"01.07.2025", status:"green", leistung:684000, pvs:662000, honorar:578000, eigenlabor:84000, ebitda:129000, marge:18.9, cashflow:54000, konto:188000, forderungen:76000, plan:7.6, kosten:{material:7.9,fremdlabor:12.7,sonstige:31.8,gesamt:62.4}, debt:{kaufpreis:760000,darlehen:520000,rest:493000,tilgung:31000,zins:23000,earnTotal:120000,earnPaid:82000,ziel:108000,ist:129000}},
  { id:"huettenberg", name:"Hüttenberg", start:"01.01.2026", status:"red", leistung:428000, pvs:411000, honorar:374000, eigenlabor:37000, ebitda:36000, marge:8.4, cashflow:12000, konto:94000, forderungen:69000, plan:-8.4, kosten:{material:12.1,fremdlabor:17.6,sonstige:44.2,gesamt:79.4}, debt:{kaufpreis:690000,darlehen:500000,rest:486000,tilgung:18000,zins:19000,earnTotal:110000,earnPaid:14000,ziel:64000,ist:36000}},
  { id:"kassel", name:"Kassel", start:"01.07.2026", status:"yellow", leistung:0, pvs:0, honorar:0, eigenlabor:0, ebitda:0, marge:0, cashflow:0, konto:0, forderungen:0, plan:0, kosten:{material:0,fremdlabor:0,sonstige:0,gesamt:0}, debt:{kaufpreis:940000,darlehen:690000,rest:690000,tilgung:0,zins:0,earnTotal:170000,earnPaid:0,ziel:0,ist:0}}
];
const months = [{m:"Jan",leistung:480000,ebitda:52000,plan:510000,cashflow:18000},{m:"Feb",leistung:522000,ebitda:68000,plan:530000,cashflow:24000},{m:"Mrz",leistung:558000,ebitda:76000,plan:550000,cashflow:37000},{m:"Apr",leistung:602000,ebitda:88000,plan:575000,cashflow:44000},{m:"Mai",leistung:646000,ebitda:93000,plan:610000,cashflow:38000},{m:"Jun",leistung:684000,ebitda:101000,plan:640000,cashflow:51000}];
const periods = ["Aktueller Monat","YTD","Letzte 3 Monate","Letzte 6 Monate","Letzte 12 Monate","Geschäftsjahr 2024","Geschäftsjahr 2025","Geschäftsjahr 2026","Gesamt seit Praxisstart","Freier Zeitraum"];
const compares = ["Ist","Plan","Vorjahr","Abweichung in EUR","Abweichung in %"];
const uploads = ["Konsolidierte Orisus-Exportdatei","BWA","PVS-Umsätze","Honorarumsätze","Eigenlaborumsätze","Offene Forderungen","Cashflow","Kontostände","Darlehen","Earn-Out","Planwerte"];
const nav = [{id:"cockpit",label:"Cockpit",icon:Home},{id:"standorte",label:"Standorte",icon:Building2},{id:"bwa",label:"BWA",icon:FileBarChart},{id:"cashflow",label:"Cashflow",icon:Wallet},{id:"plan",label:"Plan/Ist",icon:BarChart3},{id:"darlehen",label:"Darlehen & Earn-Out",icon:Landmark},{id:"uploads",label:"Uploads",icon:FileUp},{id:"reports",label:"Reports",icon:FileBarChart}] as const;
const mobile = [nav[0], nav[1], {id:"analysen",label:"Analysen",icon:BarChart3} as const, nav[5], nav[6]];

function eur(v:number, compact=false){return new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:0,notation:compact?"compact":"standard"}).format(v)}
function pct(v:number){return `${v.toLocaleString("de-DE",{maximumFractionDigits:1})} %`}
function sum(k:keyof Standort){return sites.reduce((a,s)=>a+Number(s[k]||0),0)}
function cx(...x:(string|false|undefined)[]){return x.filter(Boolean).join(" ")}
function tone(s:Status){return s==="green"?"bg-emerald-50 text-emerald-700":s==="yellow"?"bg-amber-50 text-amber-700":"bg-red-50 text-red-700"}

export default function App(){
  const [auth,setAuth]=useState<Auth>("welcome"); const [page,setPage]=useState<Page>("cockpit"); const [siteId,setSiteId]=useState("kirchberg"); const [drawer,setDrawer]=useState(false); const [pin,setPin]=useState("");
  const site=useMemo(()=>sites.find(s=>s.id===siteId)||sites[0],[siteId]);
  if(auth!=="app") return <Login auth={auth} setAuth={setAuth} pin={pin} setPin={setPin}/>;
  const go=(p:Page)=>{setPage(p);setDrawer(false)};
  return <div className="min-h-screen lg:flex">
    <aside className="fixed left-0 top-0 hidden h-screen w-72 border-r border-slate-200 bg-white/95 p-5 lg:block"><Brand/><div className="mt-8 space-y-1">{nav.map(n=><Nav key={n.id} item={n} active={page===n.id} go={go}/>)}</div><div className="absolute bottom-6 left-5 right-5 rounded-lg border bg-slate-50 p-4 text-sm"><b>Svend Neumann</b><p className="text-slate-500">Interner CFO-Zugang</p></div></aside>
    <header className="sticky top-0 z-20 border-b bg-white/90 p-4 backdrop-blur lg:hidden"><div className="flex items-center justify-between"><Brand small/><button className="grid h-10 w-10 place-items-center rounded-md border" onClick={()=>setDrawer(true)}><Menu size={20}/></button></div></header>
    {drawer&&<div className="fixed inset-0 z-40 bg-slate-950/40 lg:hidden"><div className="ml-auto h-full w-80 max-w-[86vw] bg-white p-5"><div className="flex justify-between"><Brand small/><button className="grid h-10 w-10 place-items-center rounded-md border" onClick={()=>setDrawer(false)}><X size={20}/></button></div><div className="mt-7 space-y-1">{nav.map(n=><Nav key={n.id} item={n} active={page===n.id} go={go}/>)}</div></div></div>}
    <main className="w-full px-4 pb-28 pt-5 sm:px-6 lg:ml-72 lg:px-8 lg:pb-10"><div className="mx-auto max-w-7xl"><Filters/>{page==="cockpit"&&<Cockpit go={go}/>} {page==="standorte"&&<Standorte open={(id)=>{setSiteId(id);setPage("analysen")}}/>} {page==="analysen"&&<Analysen site={site}/>} {page==="bwa"&&<Bwa/>} {page==="cashflow"&&<Cashflow/>} {page==="plan"&&<Plan/>} {page==="darlehen"&&<Darlehen/>} {page==="uploads"&&<Uploads/>} {page==="reports"&&<Reports/>}</div></main>
    <nav className="safe-bottom fixed bottom-0 left-0 right-0 z-30 border-t bg-white/95 px-2 pt-2 backdrop-blur lg:hidden"><div className="grid grid-cols-5 gap-1">{mobile.map(n=><button key={n.id} onClick={()=>go(n.id as Page)} className={cx("flex min-h-14 flex-col items-center justify-center gap-1 rounded-md text-[11px] font-bold text-slate-500",page===n.id&&"bg-cyan-50 text-cyan-800")}><n.icon size={20}/>{n.label}</button>)}</div></nav>
  </div>
}

function Login({auth,setAuth,pin,setPin}:{auth:Auth;setAuth:(a:Auth)=>void;pin:string;setPin:(p:string)=>void}){return <main className="flex min-h-screen items-center justify-center p-4"><div className="w-full max-w-md overflow-hidden rounded-lg border bg-white shadow-soft"><div className="bg-slate-950 p-6 text-white"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-md bg-cyan-500/20"><Gauge/></div><div><p className="text-sm text-cyan-100">Orisus</p><h1 className="text-xl font-bold">Orisus CFO Dashboard</h1></div></div><p className="mt-4 text-sm leading-6 text-slate-300">Wirtschaftliche Steuerung der Orisus-Gruppe. Konsolidierte Kennzahlen, Standortvergleiche, Cashflow, BWA, PVS-Umsätze, offene Forderungen, Darlehen, Earn-Outs und Liquidität auf einen Blick.</p></div><div className="space-y-4 p-6">{auth==="welcome"&&<><Btn onClick={()=>setAuth("login")}>Anmelden</Btn><Btn second onClick={()=>setAuth("forgot")}>Passwort vergessen</Btn></>}{auth==="login"&&<Form title="Anmelden" text="Dummy-Zugang für Svend Neumann."><Input defaultValue="svend.neumann@orisus.de"/><Input type="password" placeholder="Passwort"/><Btn onClick={()=>setAuth("firstPassword")}>Einloggen</Btn><button className="text-sm font-bold text-cyan-800" onClick={()=>setAuth("forgot")}>Passwort vergessen</button></Form>}{auth==="firstPassword"&&<Form title="Erstlogin" text="Neues Passwort für den Prototyp festlegen."><Input type="password" placeholder="Neues Passwort"/><Input type="password" placeholder="Passwort bestätigen"/><Btn onClick={()=>setAuth("firstPin")}>Weiter zur PIN</Btn></Form>}{auth==="firstPin"&&<Form title="PIN festlegen" text="6-stellige PIN für die reguläre Nutzung."><Input inputMode="numeric" maxLength={6} placeholder="123456" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,6))}/><Btn disabled={pin.length<6} onClick={()=>setAuth("app")}>Dashboard öffnen</Btn></Form>}{auth==="forgot"&&<Form title="Passwort zurücksetzen" text="Perspektivisch wird ein Reset-Link an svend.neumann@orisus.de gesendet."><Input defaultValue="svend.neumann@orisus.de"/><Btn onClick={()=>setAuth("login")}>Reset-Link simulieren</Btn><Btn second onClick={()=>setAuth("welcome")}>Zurück</Btn></Form>}</div></div></main>}
function Form(p:{title:string;text:string;children:React.ReactNode}){return <div className="space-y-4"><div><h2 className="text-lg font-bold">{p.title}</h2><p className="text-sm text-slate-500">{p.text}</p></div>{p.children}</div>}
function Input(p:React.InputHTMLAttributes<HTMLInputElement>){return <input {...p} className="h-11 w-full rounded-md border px-3 outline-none focus:border-cyan-800 focus:ring-4 focus:ring-cyan-800/10"/>}
function Btn(p:React.ButtonHTMLAttributes<HTMLButtonElement>&{second?:boolean}){return <button {...p} className={cx("inline-flex h-11 w-full items-center justify-center rounded-md px-4 text-sm font-bold disabled:opacity-50",p.second?"border bg-white hover:bg-slate-50":"bg-cyan-800 text-white hover:bg-cyan-900")}/>} 
function Brand({small=false}:{small?:boolean}){return <div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-md bg-cyan-800 text-white"><Gauge size={20}/></div><div><p className="text-sm font-bold">Orisus</p>{!small&&<p className="text-xs text-slate-500">CFO Dashboard</p>}</div></div>}
function Nav({item,active,go}:{item:typeof nav[number];active:boolean;go:(p:Page)=>void}){return <button onClick={()=>go(item.id as Page)} className={cx("flex h-11 w-full items-center gap-3 rounded-md px-3 text-sm font-bold text-slate-500 hover:bg-slate-100",active&&"bg-cyan-50 text-cyan-800")}><item.icon size={20}/>{item.label}</button>}
function Filters(){return <div className="mb-5 flex flex-col gap-3 rounded-lg border bg-white/90 p-3 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase text-slate-500">Globaler Filter</p><p className="text-sm font-bold">Zeitraum und Vergleich</p></div><div className="grid gap-2 sm:grid-cols-2"><select className="h-10 rounded-md border bg-white px-3 text-sm font-bold">{periods.map(x=><option key={x}>{x}</option>)}</select><select className="h-10 rounded-md border bg-white px-3 text-sm font-bold">{compares.map(x=><option key={x}>{x}</option>)}</select></div></div>}
function Title({t,d}:{t:string;d:string}){return <div><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{t}</h1><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-500">{d}</p></div>}
function Card(p:React.HTMLAttributes<HTMLDivElement>){return <div {...p} className={cx("rounded-lg border bg-white shadow-sm",p.className)}/>} 
function Badge({s}:{s:Status}){return <span className={cx("inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-bold",tone(s))}><span className={cx("h-2 w-2 rounded-full",s==="green"?"bg-emerald-500":s==="yellow"?"bg-amber-500":"bg-red-500")}/>{s==="green"?"Stabil":s==="yellow"?"Beobachten":"Handlungsbedarf"}</span>}
function Kpi({label,value,delta,status,icon:Icon,percent=false}:{label:string;value:number;delta:string;status:Status;icon:any;percent?:boolean}){const pos=!delta.startsWith("-");return <Card className="p-4"><div className="flex justify-between"><div className="grid h-10 w-10 place-items-center rounded-md bg-cyan-50 text-cyan-800"><Icon size={20}/></div><Badge s={status}/></div><p className="mt-4 text-sm font-bold text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{percent?pct(value):eur(value,true)}</p><p className={cx("mt-3 flex items-center gap-1 text-sm font-bold",pos?"text-emerald-700":"text-red-700")}>{pos?<ArrowUpRight size={16}/>:<ArrowDownRight size={16}/>} {delta}</p></Card>}
function Progress({v,s="green"}:{v:number;s?:Status}){return <div className="h-2.5 rounded-full bg-slate-100"><div className={cx("h-2.5 rounded-full",s==="green"?"bg-emerald-500":s==="yellow"?"bg-amber-500":"bg-red-500")} style={{width:`${Math.max(0,Math.min(100,v))}%`}}/></div>}
function ChartCard({title,children}:{title:string;children:React.ReactNode}){return <Card className="p-4"><h2 className="mb-4 font-bold">{title}</h2>{children}</Card>}

function Cockpit({go}:{go:(p:Page)=>void}){const k=[['Gesamtleistung gem. BWA',sum('leistung'),'+4,2 % ggü. Plan',TrendingUp,'green'],['Gesamtumsatz nach PVS',sum('pvs'),'+3,6 % ggü. Plan',BadgeEuro,'green'],['EBITDA',sum('ebitda'),'+21 TEUR ggü. Plan',Banknote,'green'],['EBITDA-Marge',13.8,'+0,9 PP',Gauge,'yellow'],['Offene Forderungen',sum('forderungen'),'+7,1 % zum Vormonat',FileBarChart,'yellow'],['Cashflow',sum('cashflow'),'+34 TEUR netto',Wallet,'green'],['Kontostand konsolidiert',sum('konto'),'Liquidität stabil',CircleDollarSign,'green']] as const;return <section className="space-y-5"><Title t="CFO Konzern Cockpit" d="Konsolidierte Steuerung der Orisus-Gruppe mit realistischen Phase-1-Dummy-Daten."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{k.map((x,i)=><Kpi key={x[0]} label={x[0]} value={x[1]} delta={x[2]} icon={x[3]} status={x[4]} percent={i===3}/>)}</div><div className="grid gap-5 xl:grid-cols-2"><Revenue/><ChartCard title="EBITDA vs. Gesamtleistung"><ResponsiveContainer width="100%" height={270}><ComposedChart data={months}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0"/><XAxis dataKey="m"/><YAxis tickFormatter={v=>eur(Number(v),true)}/><Tooltip formatter={v=>eur(Number(v))}/><Bar dataKey="leistung" fill="#0f766e" radius={[5,5,0,0]}/><Line dataKey="ebitda" stroke="#0369a1" strokeWidth={3}/></ComposedChart></ResponsiveContainer></ChartCard></div><div className="grid gap-5 xl:grid-cols-3"><Costs/><Ranking title="EBITDA je Standort" metric="ebitda"/><Ranking title="Gesamtleistung je Standort" metric="leistung"/></div><div className="grid gap-5 xl:grid-cols-2"><CashBox/><Accounts/></div><div className="grid gap-5 xl:grid-cols-2"><Traffic/><Insights go={go}/></div></section>}
function Revenue(){const h=sum('honorar'), e=sum('eigenlabor'), data=[{name:'Honorar',value:h,color:'#0f766e'},{name:'Eigenlabor',value:e,color:'#0891b2'}];return <ChartCard title="Honorarumsatz vs. Eigenlaborumsatz"><div className="grid gap-3 sm:grid-cols-[220px_1fr]"><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={data} dataKey="value" innerRadius={64} outerRadius={92} paddingAngle={4}>{data.map(d=><Cell key={d.name} fill={d.color}/>)}</Pie><Tooltip formatter={v=>eur(Number(v))}/></PieChart></ResponsiveContainer><div className="space-y-3 self-center">{data.map(d=><div key={d.name} className="rounded-md bg-slate-50 p-3"><div className="flex justify-between"><b>{d.name}</b><b>{eur(d.value)}</b></div><p className="text-sm text-slate-500">{pct(d.value/(h+e)*100)} Anteil</p></div>)}</div></div></ChartCard>}
function Costs(){const rows=[['Materialquote',9.9,10,'green'],['Fremdlaborquote',15.6,14.5,'yellow'],['Sonstige Kostenquote',37.8,36,'yellow'],['Gesamtkostenquote',69.4,68,'yellow']] as const;return <Card className="p-4"><h2 className="font-bold">Kostenquoten</h2><div className="mt-4 space-y-4">{rows.map(r=><div key={r[0]}><div className="mb-2 flex justify-between text-sm"><b>{r[0]}</b><span className="text-slate-500">Ziel {pct(r[2])}</span></div><Progress v={r[1]} s={r[3]}/><p className="mt-1 font-bold">{pct(r[1])}</p></div>)}</div></Card>}
function Ranking({title,metric}:{title:string;metric:'ebitda'|'leistung'}){return <Card className="p-4"><h2 className="font-bold">{title}</h2><div className="mt-4 space-y-3">{[...sites].sort((a,b)=>b[metric]-a[metric]).map(s=><div key={s.id} className="rounded-md bg-slate-50 p-3"><div className="mb-2 flex justify-between"><b>{s.name}</b><Badge s={s.status}/></div><div className="flex items-center gap-3"><Progress v={metric==='ebitda'?s.marge*4:s.leistung/13000} s={s.status}/><b className="min-w-20 text-right text-sm">{eur(s[metric],true)}</b></div></div>)}</div></Card>}
function CashBox(){const rows=[['Praxiseingänge',2962000],['Praxiskosten',-2014000],['Annuitäten',-251000],['Umbuchungen MVZ',-104000],['Netto-Cashflow',sum('cashflow')]] as const;return <Card className="p-4"><h2 className="font-bold">Cashflow</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{rows.map(r=><div key={r[0]} className="rounded-md bg-slate-50 p-3"><p className="text-sm text-slate-500">{r[0]}</p><p className={cx("text-xl font-bold",r[1]<0&&"text-red-700")}>{eur(r[1])}</p></div>)}</div></Card>}
function Accounts(){return <Card className="p-4"><h2 className="font-bold">Kontostände</h2><p className="mt-1 text-sm text-slate-500">Konsolidiert: {eur(sum('konto'))}</p><div className="mt-4 space-y-3">{sites.map(s=><div key={s.id} className="flex justify-between rounded-md bg-slate-50 p-3"><b>{s.name}</b><b>{eur(s.konto)}</b></div>)}</div></Card>}
function Traffic(){const rows=[['EBITDA-Marge Konzern','13,8 %','yellow'],['Cashflow Konzern',eur(sum('cashflow')),'green'],['Offene Forderungen',eur(sum('forderungen')),'yellow'],['Kostenquote','69,4 %','yellow'],['Kontostände',eur(sum('konto')),'green'],['Planabweichung','+2,4 %','green']] as const;return <Card className="p-4"><h2 className="font-bold">Ampel-Center</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{rows.map(r=><div key={r[0]} className="rounded-md border p-3"><div className="flex justify-between"><b className="text-sm">{r[0]}</b><Badge s={r[2] as Status}/></div><p className="mt-2 text-lg font-bold">{r[1]}</p></div>)}</div></Card>}
function Insights({go}:{go:(p:Page)=>void}){const x=['Cashflow Essen negativ: Annuitäten und Forderungsaufbau drücken den Netto-Cashflow.','EBITDA-Marge Ulmet liegt über Ziel.','Offene Forderungen sind konzernweit gestiegen.','Earn-Out Kirchberg bei 58 % Fortschritt.','Gesamtleistung Konzern liegt 4,2 % über Plan.','Kostenquote Kehl über Zielwert.'];return <Card className="p-4"><div className="flex justify-between"><h2 className="font-bold">CFO Insights</h2><span className="rounded-full bg-cyan-50 px-2.5 py-1 text-xs font-bold text-cyan-800">Regelbereit</span></div><div className="mt-4 space-y-3">{x.map(i=><div key={i} className="flex gap-3 rounded-md bg-slate-50 p-3"><CheckCircle2 className="mt-0.5 shrink-0 text-cyan-800" size={20}/><p className="text-sm leading-6">{i}</p></div>)}</div><button onClick={()=>go('analysen')} className="mt-4 h-11 rounded-md border px-4 text-sm font-bold">Analysen öffnen</button></Card>}
function Standorte({open}:{open:(id:string)=>void}){return <section className="space-y-5"><Title t="Standorte" d="Alle Standorte mit Zeiträumen ab jeweiligem Praxisstart."/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{sites.map(s=><Card key={s.id} className="p-4"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{s.name}</h2><p className="text-sm text-slate-500">Start: {s.start}</p></div><Badge s={s.status}/></div><div className="mt-4 grid grid-cols-2 gap-3">{[['Gesamtleistung',eur(s.leistung,true)],['EBITDA',eur(s.ebitda,true)],['Marge',pct(s.marge)],['Cashflow',eur(s.cashflow,true)],['Kontostand',eur(s.konto,true)],['Forderungen',eur(s.forderungen,true)]].map(m=><div key={m[0]} className="rounded-md bg-slate-50 p-3"><p className="text-xs font-bold text-slate-500">{m[0]}</p><b>{m[1]}</b></div>)}</div><button className="mt-4 h-11 w-full rounded-md border font-bold" onClick={()=>open(s.id)}>Standortdetail öffnen</button></Card>)}</div></section>}
function Analysen({site}:{site:Standort}){return <section className="space-y-5"><Title t="Analysen" d={`Standortdetail und Konzernanalysen. Ausgewählt: ${site.name}, Start ${site.start}.`}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Gesamtleistung" value={site.leistung} delta={`${site.plan>0?'+':''}${pct(site.plan)}`} icon={TrendingUp} status={site.status}/><Kpi label="PVS-Umsatz" value={site.pvs} delta="Plausibel zur BWA" icon={BadgeEuro} status={site.status}/><Kpi label="EBITDA" value={site.ebitda} delta={`${pct(site.marge)} Marge`} icon={Banknote} status={site.status}/><Kpi label="Cashflow" value={site.cashflow} delta="Netto nach Annuitäten" icon={Wallet} status={site.status}/></div><div className="grid gap-5 xl:grid-cols-2"><ChartCard title="EBITDA-Entwicklung"><ResponsiveContainer width="100%" height={280}><AreaChart data={months}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0"/><XAxis dataKey="m"/><YAxis tickFormatter={v=>eur(Number(v),true)}/><Tooltip formatter={v=>eur(Number(v))}/><Area dataKey="ebitda" stroke="#0369a1" fill="#dbeafe" strokeWidth={3}/></AreaChart></ResponsiveContainer></ChartCard><ChartCard title="Standortvergleich"><ResponsiveContainer width="100%" height={280}><BarChart data={sites}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0"/><XAxis dataKey="name"/><YAxis tickFormatter={v=>eur(Number(v),true)}/><Tooltip formatter={v=>eur(Number(v))}/><Bar dataKey="leistung" fill="#0f766e" radius={[5,5,0,0]}/><Bar dataKey="ebitda" fill="#0891b2" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></ChartCard></div><Plan/></section>}
function Bwa(){return <section className="space-y-5"><Title t="BWA" d="Gesamtleistung, Kostenquoten und EBITDA aus Dummy-BWA-Struktur."/><div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Gesamtleistungsentwicklung"><ResponsiveContainer width="100%" height={300}><ComposedChart data={months}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="m"/><YAxis tickFormatter={v=>eur(Number(v),true)}/><Tooltip formatter={v=>eur(Number(v))}/><Bar dataKey="leistung" fill="#0f766e"/><Line dataKey="plan" stroke="#0369a1" strokeWidth={3}/></ComposedChart></ResponsiveContainer></ChartCard><Costs/></div></section>}
function Cashflow(){return <section className="space-y-5"><Title t="Cashflow" d="Praxiseingänge, Kosten, Annuitäten, Umbuchungen MVZ und Netto-Cashflow."/><div className="grid gap-5 xl:grid-cols-2"><CashBox/><ChartCard title="Monatlicher Verlauf"><ResponsiveContainer width="100%" height={280}><AreaChart data={months}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="m"/><YAxis tickFormatter={v=>eur(Number(v),true)}/><Tooltip formatter={v=>eur(Number(v))}/><Area dataKey="cashflow" stroke="#0f766e" fill="#ccfbf1" strokeWidth={3}/></AreaChart></ResponsiveContainer></ChartCard></div><Ranking title="Standortvergleich Cashflow" metric="ebitda"/></section>}
function Plan(){return <section className="space-y-5"><Title t="Plan/Ist" d="Gesamtleistung, EBITDA und Cashflow mit Abweichungen in EUR und Prozent."/><div className="grid gap-4 lg:grid-cols-3">{[['Gesamtleistung',sum('leistung'),2.4],['EBITDA',sum('ebitda'),4.8],['Cashflow',sum('cashflow'),1.7]].map(r=><Card key={r[0] as string} className="p-4"><p className="text-sm font-bold text-slate-500">{r[0]}</p><p className="mt-2 text-2xl font-bold">{eur(r[1] as number,true)}</p><p className="text-sm font-bold text-emerald-700">+{(r[2] as number).toLocaleString('de-DE')} % vs. Plan</p></Card>)}</div><Card className="overflow-x-auto"><div className="min-w-[680px]"><div className="grid grid-cols-5 gap-2 border-b bg-slate-50 p-3 text-xs font-bold uppercase text-slate-500"><span>Standort</span><span>Ist</span><span>Plan</span><span>Abw. EUR</span><span>Abw. %</span></div>{sites.map(s=><div key={s.id} className="grid grid-cols-5 gap-2 border-b p-3 text-sm last:border-0"><b>{s.name}</b><span>{eur(s.leistung,true)}</span><span>{eur(s.leistung/(1+s.plan/100),true)}</span><span>{eur(s.leistung-s.leistung/(1+s.plan/100),true)}</span><b className={s.plan<0?'text-red-700':'text-emerald-700'}>{pct(s.plan)}</b></div>)}</div></Card></section>}
function Darlehen(){const rest=sites.reduce((a,s)=>a+s.debt.rest,0), earn=sites.reduce((a,s)=>a+s.debt.earnTotal-s.debt.earnPaid,0);return <section className="space-y-5"><Title t="Darlehen & Earn-Out" d="Kaufpreise, Restschulden, Zins, Tilgung und Earn-Out-Fortschritt je Standort."/><div className="grid gap-4 lg:grid-cols-3"><Kpi label="Gesamte Restschuld" value={rest} delta="Konsolidiert" icon={Landmark} status="yellow"/><Kpi label="Earn-Out offen" value={earn} delta="Verpflichtungen offen" icon={BadgeEuro} status="yellow"/><Kpi label="Tilgung YTD" value={251000} delta="Planmäßig" icon={Lock} status="green"/></div><div className="grid gap-4 xl:grid-cols-2">{sites.map(s=>{const prog=s.debt.earnTotal?s.debt.earnPaid/s.debt.earnTotal*100:0;return <Card key={s.id} className="p-4"><div className="flex justify-between"><h2 className="text-xl font-bold">{s.name}</h2><Badge s={s.status}/></div><div className="mt-4 grid grid-cols-2 gap-3">{[['Kaufpreis',s.debt.kaufpreis],['Darlehen',s.debt.darlehen],['Restschuld',s.debt.rest],['Tilgung',s.debt.tilgung],['Zins',s.debt.zins],['Ziel EBITDA',s.debt.ziel]].map(r=><div key={r[0] as string} className="rounded-md bg-slate-50 p-3"><p className="text-xs font-bold text-slate-500">{r[0]}</p><b>{eur(r[1] as number,true)}</b></div>)}</div><div className="mt-4"><div className="mb-2 flex justify-between text-sm"><b>Earn-Out Fortschritt</b><span>{pct(prog)}</span></div><Progress v={prog} s={prog>50?'green':'yellow'}/></div></Card>})}</div></section>}
function Uploads(){const checks=['Datei erkannt','Zeitraum erkannt','Standorte erkannt','Pflichtfelder vorhanden','Keine Dubletten','Keine Leerwerte','Summen plausibel'];return <section className="space-y-5"><Title t="Uploads" d="UI-Prototyp für die spätere konsolidierte Orisus-Power-Query-Exportdatei."/><Card className="p-4"><p className="text-sm leading-6 text-slate-500">Der echte Import wird in Phase 2 umgesetzt. Die spätere Datenbasis ist eine konsolidierte Power-Query-Exportdatei aus dem Orisus-Controlling.</p></Card><div className="grid gap-5 xl:grid-cols-2"><Card className="p-4"><h2 className="font-bold">Uploadablauf</h2><div className="mt-4 space-y-3">{['Datei auswählen','Importtyp auswählen','Zeitraum erkennen','Enthaltene Standorte erkennen','Vorschau anzeigen','Plausibilitätsprüfung anzeigen','Import bestätigen'].map((s,i)=><div key={s} className="flex items-center gap-3 rounded-md bg-slate-50 p-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-cyan-800 text-xs font-bold text-white">{i+1}</span><b>{s}</b></div>)}</div></Card><Card className="p-4"><h2 className="font-bold">Importtyp</h2><select className="mt-4 h-10 w-full rounded-md border px-3 font-bold">{uploads.map(u=><option key={u}>{u}</option>)}</select><div className="mt-4 rounded-lg border-2 border-dashed bg-slate-50 p-8 text-center"><FileUp className="mx-auto text-cyan-800" size={40}/><b className="mt-3 block">Datei auswählen</b><p className="text-sm text-slate-500">Excel oder CSV, in Phase 1 nur simuliert.</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{checks.map(c=><div key={c} className="flex items-center gap-2 rounded-md bg-emerald-50 p-3 text-sm font-bold text-emerald-800"><CheckCircle2 size={16}/>{c}</div>)}</div><button className="mt-4 h-11 w-full rounded-md bg-cyan-800 font-bold text-white">Import bestätigen</button></Card></div></section>}
function Reports(){return <section className="space-y-5"><Title t="Reports" d="Platzhalter für spätere CFO- und Bankenberichte."/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{['Monatsreport','YTD-Report','Standortreport','Bankenreport','PDF-Export später'].map(r=><Card key={r} className="p-4"><FileBarChart className="text-cyan-800" size={32}/><h2 className="mt-4 text-xl font-bold">{r}</h2><p className="mt-2 text-sm text-slate-500">Berichtsvorlage mit Dummy-Status. Exportlogik folgt in Phase 2.</p><button className="mt-4 h-11 w-full rounded-md border font-bold">Vorschau öffnen</button></Card>)}</div></section>}
